### ISSUE TITLE
Is there anyway to connect multiple chains together?

### ISSUE THREAD

**Issue by CodeAlpha7** [PacktPublishing/Learn-Blockchain-Programming-with-JavaScript#2]
Consider I have defined two blockchains with separate validator sets, let's say bc1 and bc2. Is there any way we can connects both these blockchains together in such a way that one can maintain state through block commits?
If so, how do we do this? Do we define any special API for it?

**Comment by CodeAlpha7** [comment]
Consider I have defined two blockchains with separate validator sets, let's say bc1 and bc2. Is there any way we can connects both these blockchains together in such a way that one can maintain state through block commits?

**Comment by shubham763** [comment]
Hi @CodeAlpha7 

This question is outside the range of this course. There probably are ways to connect 2 different blockchains together but that is not covered in this course.

Regards,
Shubham
